name: herons-hub
region: sgp
services:
  - name: web
    environment_slug: python
    github:
      repo: Ic3krem/Intpt-Webdev
      branch: main
      deploy_on_push: true
    source_dir: flask_backend
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    run_command: gunicorn --bind 0.0.0.0:8080 --workers 3 wsgi:app
    envs:
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FLASK_ENV
        scope: RUN_TIME
        value: production
      - key: ADMIN_DOMAIN
        scope: RUN_TIME
        value: dev.heronshub.social
      - key: MAIN_DOMAIN
        scope: RUN_TIME
        value: heronshub.social
